### ISSUE TITLE
Correção do IdAutor para IdPessoa

### ISSUE THREAD

**Issue by NathanaelSantos** [marcosdosea/Recolhaki#91]
**local: C:\Users\natha\Desktop\Dev\Recolhaki\Codigo\RecolhakiWebTests\Controllers\ManterPessoaControllerTests.cs**

Errado: var result = controller.Delete(GetTargetPessoaModel().IdAutor, GetTargetPessoaModel());

Correto: var result = controller.Delete(GetTargetPessoaModel().IdPessoa, GetTargetPessoaModel());

    
        [TestMethod()]
        public void DeleteTest_Get()
        {
            // Act
            var result = controller.Delete(GetTargetPessoaModel().IdAutor, GetTargetPessoaModel());

            // Assert
            Assert.IsInstanceOfType(result, typeof(RedirectToActionResult));
            RedirectToActionResult redirectToActionResult = (RedirectToActionResult)result;
            Assert.IsNull(redirectToActionResult.ControllerName);
            Assert.AreEqual("Index", redirectToActionResult.ActionName);

        }

**Comment by FrauzoMoura** [comment]
Já desenvolvi o que me foi solicitado, fico apenas no aguardo do meu pull request
